### ISSUE TITLE
fix: typescript 실행 방법에 따른 import 에러 처리하기

### ISSUE THREAD

**Issue by daeseong9388** [boostcampwm-2022/web20-OAO#57]
### 버그 설명

vite, jest, yarn, node, ts-node, browser 등 코드를 실행시킬 때마다 import를 처리하는 방식이 달라 생기는 에러들이 생긴다.

### 기대 동작 설명

import가 정상 작동한다

### 버그 재현법

1. `node --loader ts-node/esm`를 통해 typescript를 실행시키면 json 파일을 import하지 못한다.
2. `yarn test(jest)`를 통해 file을 읽고 쓰는 코드를 실행할 수 없다.

**Comment by kumsil1006** [comment]
[범인 잡음](https://github.com/boostcampwm-2022/web20-OAO/wiki/ESM-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%93%B0%EA%B8%B0(%EC%B6%94%ED%9B%84-%EB%B6%84%EB%A6%AC%ED%95%A0-%EC%98%88%EC%A0%95))
